
import './globals.css'
import { Inter } from 'next/font/google'
import {SorteableList} from "@/app/components/SorteableList";
import {Wrapper} from "@/app/components/Wrapper";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Wrapper>
          <div className={'flex flex-row justify-between min-h-screen'}>
              {children}
              <div className={'w-[400px] min-h-screen h-full bg-white p-4'}>
                  <SorteableList/>
              </div>
          </div>
      </Wrapper>
      </body>

    </html>
  )
}
